"""empty message

Revision ID: 98c03929a87e
Revises: 7adcf0226cd4
Create Date: 2016-06-04 19:47:00.921000

"""

# revision identifiers, used by Alembic.
revision = '98c03929a87e'
down_revision = '7adcf0226cd4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'connection_users_id_fkey', 'connection', type_='foreignkey')
    op.create_foreign_key(None, 'connection', 'users', ['user_id'], ['id'])
    op.drop_column('connection', 'users_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'connection', type_='foreignkey')
    op.create_foreign_key(u'connection_users_id_fkey', 'connection', 'users', ['users_id'], ['id'])
    op.drop_column('connection', 'user_id')
    ### end Alembic commands ###
