"""empty message

Revision ID: a622d2b06ef4
Revises: 8b7d57a1261e
Create Date: 2016-06-29 21:45:43.895000

"""

# revision identifiers, used by Alembic.
revision = 'a622d2b06ef4'
down_revision = '8b7d57a1261e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userphotocomment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['userphoto.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_photo_comment')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_photo_comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['image_id'], [u'userphoto.id'], name=u'user_photo_comment_image_id_fkey'),
    sa.ForeignKeyConstraint(['users_id'], [u'users.id'], name=u'user_photo_comment_users_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'user_photo_comment_pkey')
    )
    op.drop_table('userphotocomment')
    ### end Alembic commands ###
